### ISSUE TITLE
Feature request: Asynchronous proxy

### ISSUE THREAD

**Issue by rofr** [patriksvensson/blackbox#7]
In a high performance scenario waiting for entries to be written to the sink(or sinks) could have an unacceptable impact on performance. The BufferProxy comes closest but blocks when the buffer is full. Check out http://livedomain.codeplex.com/SourceControl/changeset/view/8378#191454 for an example implemenation pattern using a background thread.

**Comment by patriksvensson** [comment]
This is a really good idea. I will include this functionality as soon as possible. Thanks for the feedback.
